# Generated by Django 3.1.1 on 2020-09-16 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('c_code', models.TextField()),
                ('created_date_c', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date_c', models.DateTimeField(blank=True, null=True)),
                ('cpp_code', models.TextField()),
                ('created_date_cpp', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date_cpp', models.DateTimeField(blank=True, null=True)),
                ('p_code', models.TextField()),
                ('created_date_p', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date_p', models.DateTimeField(blank=True, null=True)),
                ('j_code', models.TextField()),
                ('created_date_j', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date_j', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
