# Generated by Django 3.1.1 on 2020-09-16 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeshare', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_date_c',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='published_date_c',
            new_name='published_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_date_cpp',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_date_j',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_date_p',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_date_cpp',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_date_j',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_date_p',
        ),
    ]
